<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Viewprofile_Form.aspx.cs" MasterPageFile="~/Front_Master.master" Inherits="Viewprofile_Form" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-1730637-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-1730637-1');
</script>

<link href="../admin/css/bootstrap.css" rel="stylesheet" type="text/css">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server"><!---------------------------------banner-----------------------------><div id="candidatebg"><div class="aboutblank"></div></div><!-----------------------------------divider-------------------------------------------><div id="dividerbg"></div><!----------------------------------content----------------------------------------><div id="contentbg" style="background:#eff0f1;"><div class="contentblank"><div class="main-cont"><div class="abt-lft" style="height:700px;"><div class="abt-lft-bdy1"><ul>  <li><a href="Overview_Form.aspx" class="side_menu">Overview</a></li>    <li><a href="Candidate_apply_jobs.aspx" class="side_menu">Job Applied</a></li>    <li><a href="Viewprofile_Form.aspx" class="side_menu">View Profile </a></li>    <li><a href="EditProfile_Form.aspx" class="side_menu">Edit Profile </a></li>    <li><a href="cv_upload.aspx" class="side_menu">Add Profile (Word Format) </a></li>    <li><a href="update_cv.aspx" class="side_menu">Edit Profile (Word Format) </a></li>	<li><a href="ChangePassword_Form.aspx" class="side_menu">Change Password </a></li>	<li><a href="Block_Form.aspx" class="side_menu">Block Profile </a></li>    <li class="noborder"><a href="Candidate_Logout.aspx" class="side_menu">Logout</a></li></ul></div></div><div class="abt-rht">   <p><span class="text"><H2>View Profile</H2></span>      <table class="table table-bordered" style="background:#fff;">      <tr>        <td width="40%" class="home_tx">Name </td>        <td width="60%">            <% =arr[0] %></td>      </tr>      <tr>        <td class="home_tx">Date of Birth </td>        <td><% =arr[1] %>          <% =arr[2] %>         <% =arr[3] %></td>      </tr>      <tr>        <td class="home_tx">Sex</td>        <td><% =arr[4] %></td>      </tr>      <tr>        <td class="home_tx">Marital Status</td>       <td> <% =arr[5] %></td>      </tr>      <tr>        <td class="home_tx">Email</td>        <td><% =arr[6] %></td>      </tr>      <tr>        <td class="home_tx">Address</td>        <td><% =arr[7] %></td>      </tr>      <tr>        <td class="home_tx">Country</td>        <td><% =arr[8] %></td>      </tr>      <tr>        <td class="home_tx">Current&nbsp; Location</td>        <td><% =arr[9] %></td>      </tr>      <tr>        <td class="home_tx">Telephone </td>        <td><% =arr[10] %></td>      </tr>      <tr>        <td class="home_tx">Mobile</td>        <td>                      <% =arr[11] %></td>      </tr>      <tr bgcolor="#F2F2F2">        <td colspan="2" class="home_tx"><strong>ACADEMIC/ PROFESSIONAL QUALIFICATION</strong></td>        </tr>      <tr>        <td class="home_tx">Academic qualification</td>        <td><% =arr[12] %></td>      </tr>      <tr>        <td class="home_tx">
Professional qualification</td>        <td><% =arr[13] %></td>      </tr>      <tr>        <td class="home_tx">Institute</td>        <td><% =arr[14] %></td>      </tr>      <tr>        <td class="home_tx">Year of Graduation</td>        <td><% =arr[15] %></td>      </tr>      <tr bgcolor="#F2F2F2">        <td colspan="2" class="home_tx"><strong>RESUME SUMMERY</strong></td>        </tr>      <tr>        <td class="home_tx">Resume Title</td>        <td><% =arr[16] %></td>      </tr>      <tr>        <td class="home_tx">Key Skill</td>        <td><% =arr[17] %></td>      </tr>      <tr>        <td class="home_tx">Experience</td>        <td><% =arr[18] %></td>      </tr>      <tr>        <td class="home_tx">Industry</td>        <td><% =arr[19] %></td>      </tr>      <tr>        <td class="home_tx">Functional Area</td>        <td><% =arr[20] %></td>      </tr>      <tr>        <td class="home_tx">Current Employers </td>        <td><% =arr[21] %></td>      </tr>      <tr>        <td class="home_tx">Designation</td>        <td><% =arr[22] %></td>      </tr>      <tr>        <td class="home_tx">Job Responsibility</td>        <td><% =arr[23] %></td>      </tr>      <tr>        <td class="home_tx">Period </td>        <td><% =arr[24] %></td>      </tr>      <tr>        <td class="home_tx">Summery</td>        <td><% =arr[25] %></td>      </tr>      <tr>        <td valign="top" class="home_tx">Language Known</td>        <td><% =arr[29] %>                            <% =arr[32] %>          <% =arr[33] %>                  <% =arr[34] %>                    <br />          <% =arr[30] %>          <% =arr[35] %>          <% =arr[36] %>          <% =arr[37] %>                   <br />        <% =arr[31] %>            <% =arr[38] %>           <% =arr[39] %>          <% =arr[40] %>                                      </td>      </tr>      <tr bgcolor="#F2F2F2">        <td colspan="2" class="home_tx"><strong>DESIRED&nbsp; JOB</strong></td>        </tr>      <tr>        <td class="home_tx">Job Type</td>        <td><% =arr[26] %></td>      </tr>      <tr>        <td class="home_tx">Employment Status </td>        <td><% =arr[27] %></td>      </tr>      <tr>        <td class="home_tx">Prefered Location</td>        <td><% =arr[28] %></td>      </tr>    </table>        <br /></div></div></div></div>       </asp:Content>
